name: Crowdin Download Action

on:
  schedule:
    # Run every day at 1 AM UTC
    - cron: "0 1 * * *"
  workflow_dispatch: # Manual triggering

concurrency:
  group: crowdin-download
  cancel-in-progress: true

permissions: write-all

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Skip if Crowdin ID missing
        run: |
          if [ -z "${{ secrets.CROWDIN_PROJECT_ID }}" ]; then
            echo "Skipping Crowdin sync â€” no project ID set."
            exit 0
          fi
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Synchronize with Crowdin
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_translations: true
          localization_branch_name: l10n_crowdin_translations
          create_pull_request: true
          pull_request_title: "New Crowdin translations"
          pull_request_body: "New Crowdin pull request with translations"
          pull_request_base_branch_name: "master"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_API_TOKEN: ${{ secrets.CROWDIN_API_TOKEN }}
